<?xml version="1.0"?>
<package format="2">
  <name>rolling_map</name>
  <version>2.0.0</version>
  <description>The rolling_map package</description>

  <author email="avonsternberg@lanl.gov">Alex Von Sternberg</author>
  <maintainer email="alexnavtt@lanl.gov">Alex Navarro</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>tf</build_depend>
  <build_depend>tbb</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>pcl_ros</build_depend>
  <build_depend>libomp-dev</build_depend>
  <build_depend>pcl_conversions</build_depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <build_export_depend>tf</build_export_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_depend>message_generation</build_depend>

  <exec_depend>message_runtime</exec_depend>

  <export>
  </export>
</package>
